apiVersion: v1
kind: Service
metadata:
  labels:
    app: astrid-controller
  name: controller-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    app : positive/controller
