apiVersion: v1
kind: Service
metadata:
  name: astrid-controller
  labels:
    run: astrid-controller
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  externalIPs:
    - 172.21.100.31
  selector:
    app: astrid-controller
