apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: astrid-controller
  name: controller-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: astrid-controller
  template:
    metadata:
      labels:
        app: astrid-controller
    spec:
      containers:
      - image: positive/controller
        imagePullPolicy: IfNotPresent
        name: astrid-controller
        ports:
        - containerPort: 8080
      nodeSelector:
        name: compute01
