apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: astrid-controller
  name: controller-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: astrid-controller
    spec:
      containers:
      - image: positive/controller
        name: astrid-controller
        ports:
        - containerPort: 8080
        