//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 09:25:08 AM CET 
//


package it.polito.verefoo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}NodeConstraints"/&gt;
 *         &lt;element ref="{}LinkConstraints"/&gt;
 *         &lt;element ref="{}AllocationConstraints" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeConstraints",
    "linkConstraints",
    "allocationConstraints"
})
@XmlRootElement(name = "Constraints")
public class Constraints {

    @XmlElement(name = "NodeConstraints", required = true)
    protected NodeConstraints nodeConstraints;
    @XmlElement(name = "LinkConstraints", required = true)
    protected LinkConstraints linkConstraints;
    @XmlElement(name = "AllocationConstraints")
    protected AllocationConstraints allocationConstraints;

    /**
     * Gets the value of the nodeConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link NodeConstraints }
     *     
     */
    public NodeConstraints getNodeConstraints() {
        return nodeConstraints;
    }

    /**
     * Sets the value of the nodeConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeConstraints }
     *     
     */
    public void setNodeConstraints(NodeConstraints value) {
        this.nodeConstraints = value;
    }

    /**
     * Gets the value of the linkConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link LinkConstraints }
     *     
     */
    public LinkConstraints getLinkConstraints() {
        return linkConstraints;
    }

    /**
     * Sets the value of the linkConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkConstraints }
     *     
     */
    public void setLinkConstraints(LinkConstraints value) {
        this.linkConstraints = value;
    }

    /**
     * Gets the value of the allocationConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link AllocationConstraints }
     *     
     */
    public AllocationConstraints getAllocationConstraints() {
        return allocationConstraints;
    }

    /**
     * Sets the value of the allocationConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocationConstraints }
     *     
     */
    public void setAllocationConstraints(AllocationConstraints value) {
        this.allocationConstraints = value;
    }

}
