//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 09:25:08 AM CET 
//


package it.polito.verefoo.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="protocolTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HTTP_REQUEST"/&gt;
 *     &lt;enumeration value="HTTP_RESPONSE"/&gt;
 *     &lt;enumeration value="POP3_REQUEST"/&gt;
 *     &lt;enumeration value="POP3_RESPONSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "protocolTypes")
@XmlEnum
public enum ProtocolTypes {

    HTTP_REQUEST("HTTP_REQUEST"),
    HTTP_RESPONSE("HTTP_RESPONSE"),
    @XmlEnumValue("POP3_REQUEST")
    POP_3_REQUEST("POP3_REQUEST"),
    @XmlEnumValue("POP3_RESPONSE")
    POP_3_RESPONSE("POP3_RESPONSE");
    private final String value;

    ProtocolTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProtocolTypes fromValue(String v) {
        for (ProtocolTypes c: ProtocolTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
